version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=ad_analytics
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
      - CLICKHOUSE_DB=ad_analytics
    depends_on:
      - clickhouse

  mock-data-generator:
    build:
      context: ./mock-data
      dockerfile: Dockerfile
    environment:
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
      - CLICKHOUSE_DB=ad_analytics
      - MOCK_DATA_INTERVAL_SECONDS=60
    depends_on:
      - clickhouse

  etl-worker:
    build:
      context: ./etl
      dockerfile: Dockerfile
    environment:
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin123
      - CLICKHOUSE_DB=ad_analytics
      - REDIS_URL=redis://redis:6379
    depends_on:
      - clickhouse
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  clickhouse-data: